# Generated by Django 4.2.2 on 2023-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
